import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "BoostBazar",
  description: "Generated by techloop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/favicon.png" sizes="any" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
